import com.google.inject.*;
import com.google.inject.assistedinject.Assisted;

import java.util.Map;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    static private FooFactory fooFactory;

    @Inject
    public App(FooFactory fooFactory) {
        System.out.println("App injector");
        this.fooFactory=fooFactory;
    }

    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new BinderModule());
        //Foo foo = fooFactory.create("create foo class");
        //foo.getFooName();
        Map<Key<?>,Binding<?>> map = injector.getAllBindings();
        Set<Key<?>> ks =  map.keySet();

    }
}
