import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Injector injector = Guice.createInjector(new MyModule());
        MyObject myObject = injector.getInstance(MyObject.class);
        System.out.println(myObject.getColor());

    }
}
