import com.google.inject.Binding;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Key;

import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Injector injector = Guice.createInjector(new AppModule());
        Map<Key<?>, Binding<?>> map = injector.getAllBindings();
        System.out.println("map size:"+map.size());
        Iterator<Key<?>> iter =  map.keySet().iterator();
        while (iter.hasNext()){
            Key<?> k = iter.next();
            Binding<?> b = map.get(k);
            System.out.println(k.toString());
        }
        Dog doggie = injector.getInstance(Dog.class);
        System.out.println("dog barks should see collie:");
        doggie.bark();

    }
}
